const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const storeKey='kstudio_v8';
const state=JSON.parse(localStorage.getItem(storeKey)||'{}');
function save(){['product','buy','market','niche','bookStyle','adText','planA','planB'].forEach(id=>{const el=$('#'+id); if(el) state[id]=el.value});localStorage.setItem(storeKey,JSON.stringify(state));toast('Sauvegardé');}
function load(){Object.entries(state).forEach(([k,v])=>{const el=$('#'+k); if(el) el.value=v});}
function toast(t){const b=$('#saveBtn'); const old=b.textContent;b.textContent=t==='Sauvegardé'?'✓':'✓';b.animate([{transform:'scale(1)'},{transform:'scale(.88)'},{transform:'scale(1)'}],{duration:260});setTimeout(()=>b.textContent=old,600)}
function setPill(btn){const nav=$('#segmented'),pill=$('#pill');const r=btn.getBoundingClientRect(),n=nav.getBoundingClientRect();pill.style.width=r.width+'px';pill.style.transform=`translate3d(${r.left-n.left-5}px,0,0)`}
function openPage(id){const btn=$$('[data-page]').find(b=>b.dataset.page===id);if(!btn)return;$$('.seg').forEach(b=>b.classList.toggle('active',b===btn));$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));setPill(btn);const theme=btn.dataset.theme;document.body.className=theme==='business'?'theme-business':theme==='kdp'?'theme-kdp':'theme-glass';$('#modeLabel').textContent=theme==='business'?'Business':theme==='kdp'?'KDP Soft':'Dark Glass';$('#heroTitle').textContent=id==='resale'?'Revente optimisée':id==='kdp'?'Création KDP rentable':id==='planning'?'Planning clair':'Revente, KDP & Planning';$('#heroText').textContent=id==='resale'?'Prix rapide, prix moyen, marge et annonce prête à copier.':id==='kdp'?'Idée, titre, sous-titre, mots-clés et checklist publication.':id==='planning'?'Deux plannings visibles, légende simple et organisation rapide.':'Une seule app, trois styles automatiques selon ton contexte.';window.scrollTo({top:0,behavior:'smooth'});}
function calcResale(){const product=$('#product').value||'Produit';const buy=+$('#buy').value||0;const market=+$('#market').value||0;const rapide=Math.max(0,Math.round(market*.82));const moyen=Math.round(market*.92);const max=Math.round(market*1.05);const marge=moyen-buy;const score=Math.max(1,Math.min(10,Math.round((market&&buy?((market-buy)/market)*10+4:7)*10)/10));$('#globalScore').textContent=score.toFixed(1);$('#resaleResults').innerHTML=[['Rapide',rapide+' €'],['Moyen',moyen+' €'],['Max',max+' €'],['Marge',marge+' €']].map(x=>`<div class="card mini"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('#adText').value=`${product} - très bon état\n\nJe vends ${product}. Fonctionne parfaitement, idéal pour usage perso/pro.\n\nPrix : ${moyen}€\nPrix ferme raisonnable, vente rapide possible à ${rapide}€.\n\nÀ venir chercher. Premier contact sérieux prioritaire.`;save();}
function genKdp(){const niche=$('#niche').value||'livre seniors';const style=$('#bookStyle').value;const title=niche.toLowerCase().includes('papi')?'Papi, raconte-moi ton histoire':niche.toLowerCase().includes('mamie')?'Mamie, raconte-moi ton histoire':`Mon grand livre ${niche}`;const sub=`Un livre ${style.toLowerCase()} simple, chaleureux et facile à remplir`;const kw=[niche,'livre cadeau','senior','famille','souvenirs','activité calme','grand format'].join(', ');$('#coverPreview').innerHTML=`<span>📘</span><b>${title}</b><em>${style}</em>`;$('#kdpOutput').innerHTML=`<h3>Résultat prêt à copier</h3><label>Titre<input value="${title}"></label><label>Sous-titre<textarea rows="3">${sub}</textarea></label><label>Mots-clés<textarea id="kw" rows="3">${kw}</textarea></label><button class="copy" data-copy="kw">Copier les mots-clés</button>`;save();bindCopy();}
function optPlan(){if(!$('#planA').value)$('#planA').value='💸 Matin : 1 analyse produit + 1 annonce Leboncoin\n📘 30 min : idée KDP ou correction intérieur';if(!$('#planB').value)$('#planB').value='⚙️ Après-midi : publication / photos / suivi messages\n✅ Soir : bilan rapide + priorités demain';save();}
function bindCopy(){$$('[data-copy]').forEach(b=>b.onclick=()=>{const el=$('#'+b.dataset.copy);el.select();navigator.clipboard?.writeText(el.value);b.textContent='Copié ✓';setTimeout(()=>b.textContent=b.dataset.copy==='adText'?'Copier l’annonce':'Copier les mots-clés',900)})}
$$('[data-page]').forEach(b=>b.onclick=()=>openPage(b.dataset.page));$$('[data-open]').forEach(b=>b.onclick=()=>openPage(b.dataset.open));$('#calcResale').onclick=calcResale;$('#genKdp').onclick=genKdp;$('#optPlan').onclick=optPlan;$('#saveBtn').onclick=save;$('#resetBtn').onclick=()=>{localStorage.removeItem(storeKey);location.reload()};bindCopy();load();setTimeout(()=>setPill($('.seg.active')),50);window.addEventListener('resize',()=>setPill($('.seg.active')));if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
